[build]
  publish = "public"
  command = "npm run build:netlify"
[context.production]
  environment ={  KONTENT_PROJECT_ID = "3ff4596f-6a89-00d2-deb6-e5fafb98c24d", KONTENT_LANGUAGE_CODENAMES = "en-US, cs-CZ" }
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_VERSION = "14.17.5"
[[plugins]]
  package = "netlify-plugin-gatsby-cache"
